import type { MediaItem } from "@/lib/types";

/* Biblioteca de medios. Alimenta /media, el Home y las páginas de evento.
   `eventId` enlaza el material a un evento (slug). Las miniaturas son opcionales. */
export const mediaItems: MediaItem[] = [
  {
    title: "Recap — Final Liga Municipal",
    slug: "recap-final-liga-municipal",
    type: "recap",
    category: "deportes",
    eventId: "clausura-liga-municipal-futbol",
    date: "2025-05-30",
    description: "Lo mejor de la gran final en 3 minutos.",
    city: "Cajeme, Sonora",
    tags: ["futbol", "comunidad"],
  },
  {
    title: "Entrevista — Capitanes de la final",
    slug: "entrevista-capitanes-final",
    type: "entrevista",
    category: "deportes",
    eventId: "clausura-liga-municipal-futbol",
    date: "2025-05-30",
    description: "Palabras de los protagonistas tras levantar el título.",
    city: "Cajeme, Sonora",
  },
  {
    title: "Entrevista — Artistas locales",
    slug: "entrevista-artistas-locales",
    type: "entrevista",
    category: "cultura",
    date: "2025-05-18",
    description: "Conversación con los talentos que mueven la escena del sur de Sonora.",
    city: "Navojoa, Sonora",
  },
  {
    title: "Cápsula — Detrás de cámaras",
    slug: "capsula-detras-de-camaras",
    type: "capsula",
    category: "entretenimiento",
    date: "2025-05-10",
    description: "Cómo producimos una transmisión en vivo de principio a fin.",
    city: "Navojoa, Sonora",
  },
  {
    title: "Galería — Noche de música",
    slug: "galeria-noche-de-musica",
    type: "fotogaleria",
    category: "musica",
    eventId: "noche-de-musica-en-vivo",
    date: "2025-04-27",
    description: "Las mejores fotos de una noche inolvidable.",
    city: "Navojoa, Sonora",
  },
  {
    title: "Transmisión completa — Noche de música",
    slug: "transmision-noche-de-musica",
    type: "transmision",
    category: "musica",
    eventId: "noche-de-musica-en-vivo",
    date: "2025-04-27",
    description: "Revive la velada completa, multicámara y en alta calidad.",
    city: "Navojoa, Sonora",
  },
  {
    title: "Clip — Momentos destacados",
    slug: "clip-momentos-destacados",
    type: "clip",
    category: "entretenimiento",
    date: "2025-04-15",
    description: "Un repaso rápido de lo mejor del mes en VERIDIS.",
    city: "Navojoa, Sonora",
  },
  {
    title: "Noticia — Agenda cultural de la semana",
    slug: "noticia-agenda-cultural-semana",
    type: "noticia",
    category: "noticias",
    date: "2025-04-08",
    description: "Lo que no te puedes perder en el sur de Sonora.",
    city: "Navojoa, Sonora",
  },
];
